### ISSUE TITLE
[Request] Save IP and found memory locations.

### ISSUE THREAD

**Issue by maciak** [mleeneg/SysNetCheatGUI#2]
Hi,
It would be nice if you could save the IP address of my switch.
Also great would be a way to save config for games that I've found memory adresses already.

**Comment by mleeneg** [comment]
I have added the feature for remembering last IP address entered when closed. 

About saving the cheats is possible but as of this time sys-netcheat does not support pointer addresses. Also addresses change when loading or reloading a game. Because of this I find it pointless to keep addresses that become useless when I close a game or restart my switch.

**Comment by mleeneg** [comment]
Added a open and save feature for the addresses stored..
